// Dentiva Pro - document generators: Prescription (clinical), Invoice (charge),
// Receipt (payment acknowledgement), Statement (financial history). Strictly separated.
import { PdfBuilder, ClinicBrand } from './engine';
import { Ctx } from '../services/context';
import { err } from '../../shared/errors';
import { formatDate, formatDateTime, ageOn, todayClinic } from '../../shared/dates';
import { getInvoice } from '../services/invoices';
import { getPrescription } from '../services/prescriptions';
import { patientStatement } from '../services/payments';
import { PaperSize, PAYMENT_METHOD_LABELS, PaymentMethod } from '../../shared/constants';

function brand(ctx: Ctx): ClinicBrand {
  const c = ctx.clinic();
  return {
    clinicName: c.clinicName, tagline: c.tagline, address: c.address, phone: c.phone, email: c.email,
    website: c.website, registrationNo: c.registrationNo, dentistName: c.dentistName, dentistDegrees: c.dentistDegrees,
    currencyLabel: c.currencyLabel || 'Tk', taxLabel: c.taxLabel,
    invoiceFooter: c.invoiceFooter, receiptFooter: c.receiptFooter, prescriptionFooter: c.prescriptionFooter,
    timezone: c.timezone,
  };
}

function patientLine(p: { code: string; name: string; phone?: unknown; dob?: unknown; gender?: unknown }, tz: string): [string, string][] {
  const age = ageOn(String(p.dob ?? ''), tz);
  const demo = [p.gender ? String(p.gender)[0]!.toUpperCase() + String(p.gender).slice(1) : '', age != null ? `${age} yrs` : ''].filter(Boolean).join(' · ');
  return [
    ['Patient Code', p.code],
    ['Patient Name', p.name],
    ['Age / Gender', demo || '—'],
    ['Phone', String(p.phone || '—')],
  ];
}

export async function generateInvoicePdf(ctx: Ctx, invoiceId: string, paper: PaperSize, outDir: string) {
  const data = getInvoice(ctx, invoiceId);
  if (!data) throw err.notFound('Invoice');
  const tz = ctx.clinic().timezone;
  const b = brand(ctx);
  const doc = PdfBuilder.create({
    paper, brand: b, docTitle: data.status === 'void' ? 'INVOICE (VOID)' : 'INVOICE',
    docNoLabel: 'Invoice No', docNo: data.invoice_no, dateLabel: 'Date', dateValue: formatDate(data.date, tz),
  });
  doc.section('Billed To');
  doc.kvGrid(patientLine(data.patient as never, tz));
  doc.section('Items');
  doc.table(
    [
      { key: 'desc', label: 'Description', width: 0.44 },
      { key: 'tooth', label: 'Tooth', width: 0.09, align: 'center' },
      { key: 'qty', label: 'Qty', width: 0.08, align: 'right' },
      { key: 'unit', label: 'Unit Price', width: 0.13, align: 'right' },
      { key: 'disc', label: 'Discount', width: 0.11, align: 'right' },
      { key: 'total', label: 'Amount', width: 0.15, align: 'right' },
    ],
    (data.items as { description: string; tooth: number | null; qty: number; unit_price_paisa: number; discount_paisa: number; line_total_paisa: number }[]).map((it) => ({
      desc: it.description, tooth: it.tooth ? String(it.tooth) : '—', qty: String(it.qty),
      unit: doc.money(it.unit_price_paisa), disc: it.discount_paisa ? doc.money(it.discount_paisa) : '—', total: doc.money(it.line_total_paisa),
    })),
  );
  doc.totals([
    ['Subtotal', doc.money(data.subtotal_paisa)],
    ['Discount', data.discount_paisa ? `-${doc.money(data.discount_paisa)}` : doc.money(0)],
    [`${b.taxLabel}${data.tax_bp ? ` (${(data.tax_bp / 100).toFixed(2)}%)` : ''}`, doc.money(data.tax_paisa)],
    ['Total', doc.money(data.total_paisa), true],
    ['Paid', doc.money(data.paid_paisa)],
    ['Balance Due', doc.money(Math.max(0, data.total_paisa - data.paid_paisa)), true],
  ]);
  if (data.notes) { doc.section('Notes'); doc.para(data.notes); }
  if (data.status === 'void') { doc.space(0.4); doc.para(`VOID — ${data.void_reason ?? ''}`, { italic: true }); }
  doc.space(1);
  doc.para(`Generated by ${ctx.clinic().clinicName} on ${formatDateTime(new Date().toISOString(), tz)}`, { size: 7, italic: true });
  const footer = b.invoiceFooter || 'Thank you for choosing our clinic. This invoice documents charges for services rendered.';
  return doc.save(outDir, `invoice-${data.invoice_no}.pdf`, footer);
}

export async function generateReceiptPdf(ctx: Ctx, paymentId: string, outDir: string) {
  const payment = ctx.db.prepare('SELECT * FROM payments WHERE id = ?').get(paymentId) as
    { id: string; receipt_no: string; patient_id: string; invoice_id: string | null; date: string; method: PaymentMethod; amount_paisa: number; direction: string; reference: string; notes: string; created_at: string } | undefined;
  if (!payment) throw err.notFound('Payment');
  const patient = ctx.db.prepare('SELECT code, name, phone, dob, gender FROM patients WHERE id = ?').get(payment.patient_id) as { code: string; name: string; phone: string; dob: string | null; gender: string | null };
  const invoice = payment.invoice_id ? getInvoice(ctx, payment.invoice_id) : null;
  const tz = ctx.clinic().timezone;
  const b = brand(ctx);
  const isRefund = payment.direction === 'refund';
  const doc = PdfBuilder.create({
    paper: '80MM', brand: b, docTitle: isRefund ? 'REFUND RECEIPT' : 'PAYMENT RECEIPT',
    docNoLabel: 'Receipt No', docNo: payment.receipt_no, dateLabel: 'Date', dateValue: formatDate(payment.date, tz),
  });
  doc.section('Received From');
  doc.kvGrid(patientLine(patient, tz), 1);
  doc.section(isRefund ? 'Refund Details' : 'Payment Details');
  const rows: [string, string][] = [
    ['Method', PAYMENT_METHOD_LABELS[payment.method] ?? payment.method],
    ['Invoice', invoice ? invoice.invoice_no : '—'],
  ];
  if (payment.reference) rows.push(['Reference', payment.reference]);
  doc.kvGrid(rows, 1);
  doc.space(0.2);
  doc.rule(1, '#1a202c');
  const big = doc.doc;
  big.moveDown(0.2);
  big.font('Helvetica-Bold').fontSize(8).fillColor('#5b6472').text(isRefund ? 'AMOUNT REFUNDED' : 'AMOUNT RECEIVED', doc.left, big.y, { width: doc.width, align: 'center' });
  big.font('Helvetica-Bold').fontSize(16).fillColor('#0f4c5c').text(doc.money(payment.amount_paisa), doc.left, big.y, { width: doc.width, align: 'center' });
  big.moveDown(0.15);
  doc.rule(1, '#1a202c');
  if (invoice && invoice.status === 'final') {
    doc.space(0.2);
    doc.section('Invoice Balance After This Payment');
    doc.totals([
      ['Invoice Total', doc.money(invoice.total_paisa)],
      ['Total Paid', doc.money(invoice.paid_paisa)],
      ['Balance Due', doc.money(Math.max(0, invoice.total_paisa - invoice.paid_paisa)), true],
    ]);
  }
  if (payment.notes) { doc.section('Notes'); doc.para(payment.notes); }
  doc.space(0.6);
  doc.para(`Received by: ${ctx.userName()}`, { size: 7 });
  doc.para('Signature: ____________________', { size: 7 });
  const footer = b.receiptFooter || 'This receipt acknowledges payment received. Keep it for your records.';
  return doc.save(outDir, `receipt-${payment.receipt_no}.pdf`, footer);
}

export async function generatePrescriptionPdf(ctx: Ctx, rxId: string, paper: PaperSize, outDir: string) {
  const rx = getPrescription(ctx, rxId);
  if (!rx) throw err.notFound('Prescription');
  const tz = ctx.clinic().timezone;
  const b = brand(ctx);
  const doc = PdfBuilder.create({
    paper, brand: b, docTitle: 'PRESCRIPTION', docNoLabel: 'Rx No', docNo: rx.rx_no,
    dateLabel: 'Date', dateValue: formatDate(rx.date, tz),
  });
  doc.section('Patient');
  doc.kvGrid(patientLine(rx.patient as never, tz));
  if (rx.cc.length) {
    doc.section('C/C');
    doc.para(rx.cc.join(', '));
  }
  if (rx.oe.length) {
    doc.section('O/E');
    doc.para(rx.oe.join(', '));
  }
  if (rx.re) { doc.section('R/E'); doc.para(rx.re); }
  if (rx.items.length) {
    doc.section('Rx / Medications');
    doc.table(
      [
        { key: 'drug', label: 'Medication', width: 0.34 },
        { key: 'dose', label: 'Dose', width: 0.16 },
        { key: 'freq', label: 'Frequency', width: 0.18 },
        { key: 'dur', label: 'Duration', width: 0.14 },
        { key: 'route', label: 'Route', width: 0.18 },
      ],
      rx.items.map((it) => ({
        drug: `${it.drug_name}${it.strength ? ` ${it.strength}` : ''}${it.instructions ? `\n${it.instructions}` : ''}`,
        dose: it.dose || '—', freq: it.frequency || '—', dur: it.duration || '—', route: it.route || 'oral',
      })) as never[],
    );
  }
  if (rx.advice) { doc.section('Advice'); doc.para(rx.advice); }
  if (rx.follow_up_date) { doc.space(0.2); doc.para(`Follow-up: ${formatDate(rx.follow_up_date, tz)}`, { italic: true }); }
  doc.space(1.4);
  const d = doc.doc;
  d.font('Helvetica-Bold').fontSize(9).fillColor('#1a202c').text(b.dentistName || '', doc.left, d.y, { align: 'right', width: doc.width });
  d.font('Helvetica').fontSize(7.5).fillColor('#5b6472').text(b.dentistDegrees || '', doc.left, d.y, { align: 'right', width: doc.width });
  const footer = b.prescriptionFooter || 'This prescription is a clinical document. It is not an invoice or payment receipt.';
  return doc.save(outDir, `prescription-${rx.rx_no}.pdf`, footer);
}

export async function generateStatementPdf(ctx: Ctx, patientId: string, range: { from?: string; to?: string }, paper: PaperSize, outDir: string) {
  const st = patientStatement(ctx, { patientId, from: range.from, to: range.to });
  const tz = ctx.clinic().timezone;
  const b = brand(ctx);
  const doc = PdfBuilder.create({
    paper, brand: b, docTitle: 'ACCOUNT STATEMENT',
    docNoLabel: 'Patient', docNo: st.patient.code, dateLabel: 'Generated',
    dateValue: formatDate(todayClinic(tz), tz),
  });
  doc.section('Account Holder');
  doc.kvGrid([
    ['Patient Code', st.patient.code], ['Patient Name', st.patient.name],
    ['Period', `${st.from ? formatDate(st.from, tz) : 'Beginning'} → ${st.to ? formatDate(st.to, tz) : 'To date'}`], ['Phone', st.patient.phone || '—'],
  ]);
  doc.section('Transactions');
  doc.table(
    [
      { key: 'date', label: 'Date', width: 0.12 },
      { key: 'ref', label: 'Reference', width: 0.16 },
      { key: 'desc', label: 'Description', width: 0.32 },
      { key: 'debit', label: 'Billed', width: 0.13, align: 'right' },
      { key: 'credit', label: 'Paid', width: 0.13, align: 'right' },
      { key: 'bal', label: 'Balance', width: 0.14, align: 'right' },
    ],
    st.lines.map((l) => ({
      date: formatDate(l.date, tz), ref: l.ref, desc: l.description || '—',
      debit: l.debitPaisa ? doc.money(l.debitPaisa) : '',
      credit: l.creditPaisa ? doc.money(l.creditPaisa) : '',
      bal: doc.moneySigned(l.balancePaisa),
    })),
  );
  doc.totals([
    ['Opening Balance', doc.moneySigned(st.openingPaisa)],
    ['Total Billed (all time)', doc.money(st.totals.billedAllTimePaisa)],
    ['Total Paid (all time)', doc.money(st.totals.paidPaisa)],
    ['Total Refunded (all time)', doc.money(st.totals.refundedPaisa)],
    ['Closing Balance (Outstanding)', doc.moneySigned(Math.max(0, st.totals.outstandingPaisa)), true],
  ]);
  const footer = `Statement as of ${formatDate(todayClinic(tz), tz)}. Please contact the clinic with any questions about your account.`;
  return doc.save(outDir, `statement-${st.patient.code}.pdf`, footer);
}
